apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  containers:
  - name: con1
    image: ubuntu:22.04
    command: ["/bin/bash", "-c"]
    args:
      - |
        echo "Starting Ubuntu container...";
        apt-get update && apt-get install -y curl;
        echo "Hello from Ubuntu container!" > /data/hello.txt;
        echo "File written to /data/hello.txt";
        sleep 3600
    volumeMounts:
      - name: hostpath-volume
        mountPath: /data

  volumes:
  - name: hostpath-volume
    hostPath:
      path: /tmp/hostpath-demo
      type: DirectoryOrCreate
