apiVersion: batch/v1
kind: Job
metadata:
  name: ubuntu-job
spec:
  parallelism: 5
  template:
    spec:
      containers:
      - name: testjob
        image: ubuntu:20.04
        command: ["/bin/bash", "-c"]
        args:
          - |
            echo "Updating Ubuntu container...";
            apt-get update -y;
            echo "Update complete!";
      restartPolicy: Never
