apiVersion: v1
kind: Pod
metadata:
  name: httpd-dev
  labels:
    app: webserver
    env: dev
spec:
  containers:
    - name: httpd
      image: httpd:latest
      ports:
        - containerPort: 80
  nodeSelector:
    name: node1
