apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
spec:
  replicas: 3
  selector:
    app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:latest
          ports:
            - containerPort: 80
      nodeSelector:
        name: node1
