apiVersion: v1
kind: Pod
metadata:
  name: resource-test
  labels:
    app: httpd
spec:
  containers:
    - name: httpd-container
      image: httpd:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "200m"      # 0.2 CPU core (200 millicores)
          memory: "256Mi"  # 256 MB RAM guaranteed
        limits:
          cpu: "500m"      # Max 0.5 CPU core
          memory: "512Mi"  # Max 512 MB RAM
