apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rs
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: env
        operator: In
        values:
          - dev
          - test
  template:
    metadata:
      labels:
        app: httpd
        env: dev
    spec:
      containers:
        - name: httpd
          image: httpd:latest
