kind: Pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
  - name: c1
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do echo Hello-Keshav; sleep 5 ; done"]

  - name: c2
    image: httpd
    ports:
    - containerPort: 80
